name: Flutter CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Create Secret
        run: echo "googleMapsApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" > dart_defines/local.env

      - name: Build Android
        run: flutter build apk --release --dart-define-from-file=dart_defines/local.env

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-android
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Create Secret
        run: echo "googleMapsApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" > dart_defines/local.env

      - name: Build iOS
        run: flutter build ios --no-codesign --dart-define-from-file=dart_defines/local.env

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ios
          path: build/ios/iphoneos/Runner.app
